---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'https://api.mealviewer.com/api/v4/school/{{ mealviewer_school_id }}/{{ ''now'' | date: ''%s'' | minus: 604800 | date: ''%Y-%m-%d'' }}/{{ ''now'' | date: ''%s'' | plus: 604800 | date: ''%Y-%m-%d'' }}/0'
polling_headers: content-type=application/json
polling_body: ''
id: 133879
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Shows school lunch menu via MealViewer.com
  github_url: https://github.com/stephenyeargin/trmnl-mealviewer
  learn_more_url: https://mealviewer.com
  email_address: stephen@yearg.in
- keyname: mealviewer_school_id
  field_type: string
  name: School ID
  description: The identifier for the school, usually <a href="https://schools.mealviewer.com/">found in the URL</a>.
  placeholder: SpringfieldElementary
- keyname: mealviewer_blocks_to_display
  field_type: select
  name: Menus to Display
  description: Select Meals
  options:
  - Breakfast: Breakfast
  - Lunch: Lunch
  - Pre-K Breakfast: Pre-K Breakfast
  - Pre-K Lunch: Pre-K Lunch
  multiple: true
name: MealViewer (School Lunch)
refresh_interval: 1440
